### Biblioteki

In [2]:
import numpy as np
from numpy.linalg import det, inv, norm
import sympy as sp  #biblioteka umozliwiajaca operacje symboliczne

### Losowe generowanie macierzy

In [8]:
np.set_printoptions(precision=5, suppress=False, floatmode='fixed')
tolerance=1e-20
n=5

A=np.random.randint(low=0, high=10, size=(n, n)) #macierz, na której będziemy wykonywać wszelkie operacje
B=np.random.randint(low=0, high=10, size=(n, n)) #macierz do testu mnożenia

print("Macierz A: ")
print(A)
print("Macierz B: ")
print(B)

Z=A
k=0

Macierz A: 
[[2 3 0 4 2]
 [9 7 8 0 6]
 [0 5 5 6 6]
 [9 7 3 9 7]
 [0 4 2 9 7]]
Macierz B: 
[[6 0 6 3 1]
 [9 6 3 2 0]
 [4 8 1 1 8]
 [8 2 0 2 0]
 [2 5 8 2 8]]


### Postać schodkowa

In [9]:
def schodkowa(A):
    k=0
    A = A.copy().astype(float) #tworzy kopię i operacje wykonujemy na niej
    n = A.shape[0]
    if np.all(A == 0): #jeśli macierz jest wypełniona samymi zerami, to jest w postaci schodkowej
        return A
    current_row = 0
    for col in range(n): #przechodzimy przez kolejne kolumny
        pivot_row = None
        for row in range(current_row, n): #szukamy pierwszego niezerowego elementu w kolumnie)
            if abs(A[row, col]) > tolerance:  #używamy tolerancji dla błędów numerycznych
                pivot_row = row
                break
        if pivot_row is None: #jeśli cała kolumna jest zerowa, przechodzimy do następnej
            continue
        if pivot_row != current_row: #aby mieć niezerowy element w pierwszym wierszu, zamieniamy wiersze
            A[[current_row, pivot_row]] = A[[pivot_row, current_row]]
            k+=1
        for row in range(current_row + 1, n): #stosujemy eliminację w kolumnie
            if abs(A[row, col]) > tolerance:
                multiplier = A[row, col] / A[current_row, col]
                A[row, col:] = A[row, col:] - multiplier * A[current_row, col:]
        current_row += 1
        if current_row >= n:
            break

    return A,k

In [10]:
aret,kret=schodkowa(A)
print("Postac schodkowa macierzy: ")
print(aret)

Postac schodkowa macierzy: 
[[  2.00000   3.00000   0.00000   4.00000   2.00000]
 [  0.00000  -6.50000   8.00000 -18.00000  -3.00000]
 [  0.00000   0.00000  11.15385  -7.84615   3.69231]
 [  0.00000   0.00000   0.00000   5.48276   2.65517]
 [  0.00000   0.00000   0.00000   0.00000   1.50943]]


### Postać zredukowana

In [11]:
def zredukowana(A):
    B=aret.transpose()
    bret,kret1=schodkowa(B)
    return bret

In [12]:
bret = zredukowana(aret)
print("Postac zredukowana macierzy: ")
print(bret)

Postac zredukowana macierzy: 
[[ 2.00000  0.00000  0.00000  0.00000  0.00000]
 [ 0.00000 -6.50000  0.00000  0.00000  0.00000]
 [ 0.00000  0.00000 11.15385  0.00000  0.00000]
 [ 0.00000  0.00000  0.00000  5.48276  0.00000]
 [ 0.00000  0.00000  0.00000  0.00000  1.50943]]


### Wyznacznik macierzy

In [13]:
def wyznacznik(A):
    n=A.shape[0]
    m=1
    m=float(m)
    for i in range(n):
        m*=float(A[i,i])
    m*=(-1)**(kret%2)
    return m

In [14]:
print("Wyznacznik macierzy: ")
print(wyznacznik(aret))

Wyznacznik macierzy: 
-1199.9999999999993


### Ślad macierzy

In [15]:
def slad(A):
    q=0
    n = A.shape[0]
    for i in range(n):
        q+=A[i,i]
    return q

In [16]:
print("Slad macierzy: ")
print(slad(A))

Slad macierzy: 
30


### Rząd macierzy

In [17]:
def rzad(A):
    n=A.shape[0]
    if np.all(A == 0):
        return 0
    a=0
    i=0
    for i in range(n):
        if abs(A[i,i])>tolerance:
            a+=1
    return a

In [18]:
print("Rzad macierzy: ")
print(rzad(bret))

Rzad macierzy: 
5


### Macierz transponowana

In [19]:
def transpozycja(A):
  A = A.copy().astype(float)
  m=A.shape[0]  #liczba wierszy macierzy
  n=A.shape[1]  #liczba kolumn macierzy
  X = np.zeros((n,m), dtype=float) #pusta macierz o wymiarach n x m

  for i in range (m):
    for j in range (n):
      X[j,i]=A[i,j] #operacja transponowania

  return X

In [20]:
print("Macierz transponowana: ")
print(transpozycja(A))

Macierz transponowana: 
[[2.00000 9.00000 0.00000 9.00000 0.00000]
 [3.00000 7.00000 5.00000 7.00000 4.00000]
 [0.00000 8.00000 5.00000 3.00000 2.00000]
 [4.00000 0.00000 6.00000 9.00000 9.00000]
 [2.00000 6.00000 6.00000 7.00000 7.00000]]


### Mnożenie macierzy

In [21]:
def mnozenie(A,B):
  mA=A.shape[0]
  nA=A.shape[1]
  mB=B.shape[0]
  nB=B.shape[1]
  if nA!=mB: #warunek konieczny mnozenia macierzy
    print ("Tych macierzy nie da sie pomnozyc")
    return ""
  X=np.zeros((mA,nB), dtype=float) #pusta macierz o wymiarach wiersze A x kolumny B
  for i in range (mA):
    for j in range (nB):
      for k in range (nA):
        X[i,j]+=A[i,k]*B[k,j] #mnozenie macierzy
  return X

In [22]:
print ("Wynik mnozenia macierzy: ")
print (mnozenie(A,B))

Wynik mnozenia macierzy: 
[[ 75.00000  36.00000  37.00000  24.00000  18.00000]
 [161.00000 136.00000 131.00000  61.00000 121.00000]
 [125.00000 112.00000  68.00000  39.00000  88.00000]
 [215.00000 119.00000 134.00000  76.00000  89.00000]
 [130.00000  93.00000  70.00000  42.00000  72.00000]]


### Macierz odwrotna

In [23]:
def minor(A,i,j):  #funkcja pomocnicza, wyznaczajaca minory
  A = A.copy().astype(float)
  M = np.delete(A, i, axis=0)  #usuniecie i-tego wiersza
  M = np.delete(M, j, axis=1)  #usuniecie j-tej kolumny
  return M

In [24]:
def odwrotna(A):
  A = A.copy().astype(float)
  m=A.shape[0]
  n=A.shape[1]  #wymiary macierzy A

  if m!=n:  #sprawdzanie zgodnosci wymiarow
    print ("Macierz odwrotna nie istnieje")
    return ""

  if abs(wyznacznik(A))<tolerance:
    print ("Macierz odwrotna nie istnieje") #warunek na odwracalnosc macierzy
    return ""

  X = np.zeros((m,n), dtype=float) #pusta macierz, wynik odwrotnosci
  for i in range (n):
    for j in range (m):
      X[i,j]=((-1)**(i+j))*wyznacznik(minor(A,i,j))  # macierz stowarzyszona

  X=transpozycja(X)
  X=X/wyznacznik(A)
  return X

In [25]:
print ("Macierz odwrotna: ")
print (odwrotna(A))

Macierz odwrotna: 
[[ 0.50000 -0.21429  0.34286 -0.22857  0.22857]
 [-0.64286  0.14286 -0.22857  0.15238 -0.15238]
 [ 0.64286 -0.14286  0.20000 -0.13333  0.13333]
 [-0.21429  0.04762 -0.06667  0.11111 -0.11111]
 [ 0.27551 -0.06122  0.08571 -0.14286  0.14286]]


### Wielomian charakterystyczny

In [26]:
def wielomian_charakterystyczny(A):
    A = A.copy().astype(float)
    m= A.shape[0]
    n=A.shape[1]  #wymiary macierzy A
    if m != n:
        print("Macierz nie jest kwadratowa – nie można wyznaczyć wielomianu.")
        return ""

    λ = sp.symbols('λ')  #symbol lambda, uzywany do zapisu wielomianu
    X = sp.Matrix(A)  #konwersja na macierz w sympy
    I = sp.zeros(n,n)
    for i in range (n):
      I[i,i]= 1  #generowanie macierzy jednostkowej

    X = X - λ * I  #w_A(\lambda)=\det(A-\lambda I),
    wyzn= sp.simplify(X.det())  #wyznacznik macierzy X, uproszczenie
    wielomian = sp.Poly(wyzn, λ)  #utworzenie wielomianu ze zmienna \lambda
    return wielomian

In [27]:
print("Wielomian charakterystyczny:")
print(wielomian_charakterystyczny(A).as_expr())

Wielomian charakterystyczny:
-1.0*λ**5 + 30.0*λ**4 - 126.0*λ**3 - 147.0*λ**2 + 1786.0*λ - 1200.0


### Sprawdzanie przynależności do grup liniowych

In [28]:
def is_GL(A):
    """
    Sprawdzenie czy macierz należy do GL(n)
    Macierz należy do GL(n) jeśli jest odwracalna
    """
    return abs(wyznacznik(A)) > tolerance

def is_SL(A):
    """
    Sprawdzenie czy macierz należy do SL(n)
    Macierz należy do SL(n) jeśli należy do GL(n) i det = 1
    """
    return abs(wyznacznik(A) - 1) < tolerance

def is_orthogonal(A):
    """
    Sprawdzenie czy macierz należy do O(n)
    Macierz należy do O(n) jeśli A^{-1} = A^T
    """
    return np.allclose(A @ A.T, np.eye(A.shape[0]), atol=tolerance)

def is_SO(A):
    """
    Sprawdzenie czy macierz należy do SO(n)
    j.w., należy do O(n) oraz det =1
    """
    return is_orthogonal(A) and abs(wyznacznik(A) - 1) < tolerance

def is_unitary(A):
    """
    Sprawdzenie czy macierz należy do U(n)
    Macierz należy do U(n) jeśli A^{-1} = A^*
    """
    return np.allclose(A @ A.conj().T, np.eye(A.shape[0]), atol=tolerance)

def is_SU(A):
    """
    Sprawdzenie czy macierz należy do SU(n)
    Należy do SU(n), jeśli należy do U(n) i det = 1
    """
    return is_unitary(A) and abs(wyznacznik(A) - 1) < tolerance

def is_symplectic(A):
    """
    Sprawdzenie czy macierz należy do grupy symplektycznej Sp(2n)
    Macierz M jest symplektyczna jeśli jest macierzą niezdeg. antysym. formy dwuliniowej, czyli M^T J M = J gdzie J = [0 I; -I 0]
    """
    n = A.shape[0]
    if n % 2 != 0:
        return False  # Wymiar musi być parzysty

    # Tworzymy macierz J
    m = n // 2
    J = np.block([[np.zeros((m, m)), np.eye(m)],
                  [-np.eye(m), np.zeros((m, m))]])

    return np.allclose(A.T @ J @ A, J, atol=tolerance)

In [5]:
def check_matrix_groups(A):
    """
    Polecenie zwraca booleanowy słownik, gdzie kluczami są grupy liniowe
    """
    results = {
        'GL': is_GL(A),
        'SL': is_SL(A),
        'O': is_orthogonal(A),
        'SO': is_SO(A),
        'U': is_unitary(A),
        'SU': is_SU(A),
        'Sp': is_symplectic(A)
    }
    return results

### Przykłady

In [30]:
identity = np.eye(2)
rotation = np.array([[0.6, -0.8], [0.8, 0.6]])  # SO(2)
unitary = np.array([[1j,1],[1,1j]]) / np.sqrt(2) # SU(2)
symplectic = np.array([[1, 0, 1, 0],
                          [0, 1, 0, 1],
                          [0, 0, 1, 0],
                          [0, 0, 0, 1]])  # niesymplekt.

print("id:")
print(check_matrix_groups(identity))

print("SO:")
print(check_matrix_groups(rotation))

print("U:")
print(check_matrix_groups(unitary))

print("Sp:")
print(check_matrix_groups(symplectic))

print("A:")
print(check_matrix_groups(A))

id:
{'GL': True, 'SL': True, 'O': True, 'SO': True, 'U': True, 'SU': True, 'Sp': True}
SO:
{'GL': True, 'SL': False, 'O': False, 'SO': False, 'U': False, 'SU': False, 'Sp': False}
U:
{'GL': False, 'SL': False, 'O': False, 'SO': False, 'U': True, 'SU': False, 'Sp': False}
Sp:
{'GL': True, 'SL': True, 'O': False, 'SO': False, 'U': False, 'SU': False, 'Sp': True}
A:
{'GL': True, 'SL': False, 'O': False, 'SO': False, 'U': False, 'SU': False, 'Sp': False}


<ipython-input-13-6398d1585878>:6: ComplexWarning: Casting complex values to real discards the imaginary part
  m*=float(A[i,i])
