### Biblioteki

In [2]:
import numpy as np
from numpy.linalg import det, inv, norm
import sympy as sp  #biblioteka umozliwiajaca operacje symboliczne

### Losowe generowanie macierzy

In [3]:
np.set_printoptions(precision=5, suppress=False, floatmode='fixed')
tolerance=1e-20
n=5

A=np.random.randint(low=0, high=10, size=(n, n)) #macierz, na której będziemy wykonywać wszelkie operacje
B=np.random.randint(low=0, high=10, size=(n, n)) #macierz do testu mnożenia

print("Macierz A: ")
print(A)
print("Macierz B: ")
print(B)

Z=A
k=0

Macierz A: 
[[4 7 2 8 5]
 [6 5 4 6 6]
 [2 6 6 6 4]
 [6 2 2 0 0]
 [8 9 9 4 0]]
Macierz B: 
[[5 5 7 0 0]
 [4 9 7 3 0]
 [8 9 4 3 3]
 [8 3 6 7 5]
 [5 7 6 8 5]]


### Postać schodkowa

In [4]:
def schodkowa(A):
    k=0
    A = A.copy().astype(float) #tworzy kopię i operacje wykonujemy na niej 
    n = A.shape[0]
    if np.all(A == 0): #jeśli macierz jest wypełniona samymi zerami, to jest w postaci schodkowej
        return A
    current_row = 0
    for col in range(n): #przechodzimy przez kolejne kolumny
        pivot_row = None
        for row in range(current_row, n): #szukamy pierwszego niezerowego elementu w kolumnie)
            if abs(A[row, col]) > tolerance:  #używamy tolerancji dla błędów numerycznych
                pivot_row = row
                break 
        if pivot_row is None: #jeśli cała kolumna jest zerowa, przechodzimy do następnej
            continue       
        if pivot_row != current_row: #aby mieć niezerowy element w pierwszym wierszu, zamieniamy wiersze
            A[[current_row, pivot_row]] = A[[pivot_row, current_row]]
            k+=1
        for row in range(current_row + 1, n): #stosujemy eliminację w kolumnie
            if abs(A[row, col]) > tolerance: 
                multiplier = A[row, col] / A[current_row, col]
                A[row, col:] = A[row, col:] - multiplier * A[current_row, col:]
        current_row += 1
        if current_row >= n:
            break
    
    return A,k

In [5]:
aret,kret=schodkowa(A)
print("Postac schodkowa macierzy: ")
print(aret)

Postac schodkowa macierzy: 
[[ 4.00000  7.00000  2.00000  8.00000  5.00000]
 [ 0.00000 -5.50000  1.00000 -6.00000 -1.50000]
 [ 0.00000  0.00000  5.45455 -0.72727  0.81818]
 [ 0.00000  0.00000  0.00000 -3.06667 -4.80000]
 [ 0.00000  0.00000  0.00000  0.00000  0.14130]]


### Postać zredukowana

In [6]:
def zredukowana(A):
    B=aret.transpose()
    bret,kret1=schodkowa(B)
    return bret

In [7]:
bret = zredukowana(aret)
print("Postac zredukowana macierzy: ")
print(bret)

Postac zredukowana macierzy: 
[[ 4.00000  0.00000  0.00000  0.00000  0.00000]
 [ 0.00000 -5.50000  0.00000  0.00000  0.00000]
 [ 0.00000  0.00000  5.45455  0.00000  0.00000]
 [ 0.00000  0.00000  0.00000 -3.06667  0.00000]
 [ 0.00000  0.00000  0.00000  0.00000  0.14130]]


### Wyznacznik macierzy

In [8]:
def wyznacznik(A):
    n=A.shape[0]
    m=1
    m=float(m)
    for i in range(n):
        m*=float(A[i,i])
    m*=(-1)**(kret%2)
    return m

In [9]:
print("Wyznacznik macierzy: ")
print(wyznacznik(aret))

Wyznacznik macierzy: 
52.00000000000095


### Ślad macierzy

In [10]:
def slad(A):
    q=0
    n = A.shape[0]
    for i in range(n):
        q+=A[i,i]
    return q

In [11]:
print("Slad macierzy: ")
print(slad(A))

Slad macierzy: 
15


### Rząd macierzy

In [12]:
def rzad(A):
    n=A.shape[0]
    if np.all(A == 0): 
        return 0
    a=0
    i=0
    for i in range(n):
        if abs(A[i,i])>tolerance:
            a+=1
    return a

In [13]:
print("Rzad macierzy: ")
print(rzad(bret))

Rzad macierzy: 
5


### Macierz transponowana

In [14]:
def transpozycja(A):
  A = A.copy().astype(float)
  m=A.shape[0]  #liczba wierszy macierzy
  n=A.shape[1]  #liczba kolumn macierzy 
  X = np.zeros((n,m), dtype=float) #pusta macierz o wymiarach n x m

  for i in range (m):
    for j in range (n):
      X[j,i]=A[i,j] #operacja transponowania

  return X

In [15]:
print("Macierz transponowana: ")
print(transpozycja(A))

Macierz transponowana: 
[[4.00000 6.00000 2.00000 6.00000 8.00000]
 [7.00000 5.00000 6.00000 2.00000 9.00000]
 [2.00000 4.00000 6.00000 2.00000 9.00000]
 [8.00000 6.00000 6.00000 0.00000 4.00000]
 [5.00000 6.00000 4.00000 0.00000 0.00000]]


### Mnożenie macierzy

In [191]:
def mnozenie(A,B):
  mA=A.shape[0]
  nA=A.shape[1]
  mB=B.shape[0]
  nB=B.shape[1]
  if nA!=mB: #warunek konieczny mnozenia macierzy
    print ("Tych macierzy nie da sie pomnozyc")
    return ""
  X=np.zeros((mA,nB), dtype=float) #pusta macierz o wymiarach wiersze A x kolumny B
  for i in range (mA):
    for j in range (nB):
      for k in range (nA):
        X[i,j]+=A[i,k]*B[k,j] #mnozenie macierzy
  return X

In [192]:
print ("Wynik mnozenia macierzy: ")
print (mnozenie(A,B))

Wynik mnozenia macierzy: 
[[ 30.00000  95.00000 125.00000 107.00000 157.00000]
 [ 61.00000 102.00000 114.00000 122.00000 171.00000]
 [ 36.00000  60.00000 102.00000  90.00000 139.00000]
 [ 54.00000  76.00000 136.00000 111.00000 176.00000]
 [ 36.00000  71.00000  57.00000  80.00000  95.00000]]


### Macierz odwrotna

In [193]:
def minor(A,i,j):  #funkcja pomocnicza, wyznaczajaca minory
  A = A.copy().astype(float)
  M = np.delete(A, i, axis=0)  #usuniecie i-tego wiersza
  M = np.delete(M, j, axis=1)  #usuniecie j-tej kolumny
  return M

In [194]:
def odwrotna(A):
  A = A.copy().astype(float)
  m=A.shape[0]
  n=A.shape[1]  #wymiary macierzy A
  
  if m!=n:  #sprawdzanie zgodnosci wymiarow
    print ("Macierz odwrotna nie istnieje")
    return ""

  if abs(wyznacznik(A))<tolerance:
    print ("Macierz odwrotna nie istnieje") #warunek na odwracalnosc macierzy
    return ""

  X = np.zeros((m,n), dtype=float) #pusta macierz, wynik odwrotnosci
  for i in range (n):
    for j in range (m):
      X[i,j]=((-1)**(i+j))*wyznacznik(minor(A,i,j))  # macierz stowarzyszona
  
  X=transpozycja(X)
  X=X/wyznacznik(A)
  return X

In [195]:
print ("Macierz odwrotna: ")
print (odwrotna(A))

Macierz odwrotna: 
[[ 0.12500 -0.08333  0.09524 -0.00000  0.00000]
 [-0.04167  0.11111 -0.12698  0.00000 -0.00000]
 [ 0.02976 -0.07937  0.14286 -0.00000  0.00000]
 [-0.26786  0.71429 -1.28571  1.00000 -4.50000]
 [ 0.53571 -1.42857  2.57143 -2.00000  0.50000]]


### Wielomian charakterystyczny

In [196]:
def wielomian_charakterystyczny(A):
    A = A.copy().astype(float)
    m= A.shape[0]
    n=A.shape[1]  #wymiary macierzy A
    if m != n:
        print("Macierz nie jest kwadratowa – nie można wyznaczyć wielomianu.")
        return ""

    λ = sp.symbols('λ')  #symbol lambda, uzywany do zapisu wielomianu
    X = sp.Matrix(A)  #konwersja na macierz w sympy
    I = sp.zeros(n,n)
    for i in range (n):
      I[i,i]= 1  #generowanie macierzy jednostkowej

    X = X - λ * I  #w_A(\lambda)=\det(A-\lambda I), 
    wyzn= sp.simplify(X.det())  #wyznacznik macierzy X, uproszczenie
    wielomian = sp.Poly(wyzn, λ)  #utworzenie wielomianu ze zmienna \lambda
    return wielomian

In [197]:
print("Wielomian charakterystyczny:")
print(wielomian_charakterystyczny(A).as_expr())

Wielomian charakterystyczny:
-1.0*λ**5 + 27.0*λ**4 - 26.0*λ**3 - 538.0*λ**2 + 458.0*λ - 652.0


### Sprawdzanie przynależności do grup liniowych

In [198]:
def is_GL(A):
    """
    Sprawdzenie czy macierz należy do GL(n)
    Macierz należy do GL(n) jeśli jest odwracalna
    """
    return abs(wyznacznik(A)) > tolerance

def is_SL(A):
    """
    Sprawdzenie czy macierz należy do SL(n)
    Macierz należy do SL(n) jeśli należy do GL(n) i det = 1
    """
    return abs(wyznacznik(A) - 1) < tolerance

def is_orthogonal(A):
    """
    Sprawdzenie czy macierz należy do O(n)
    Macierz należy do O(n) jeśli A^{-1} = A^T
    """
    return np.allclose(A @ A.T, np.eye(A.shape[0]), atol=tolerance)

def is_SO(A):
    """
    Sprawdzenie czy macierz należy do SO(n)
    j.w., należy do O(n) oraz det =1
    """
    return is_orthogonal(A) and abs(wyznacznik(A) - 1) < tolerance

def is_unitary(A):
    """
    Sprawdzenie czy macierz należy do U(n)
    Macierz należy do U(n) jeśli A^{-1} = A^*
    """
    return np.allclose(A @ A.conj().T, np.eye(A.shape[0]), atol=tolerance)

def is_SU(A):
    """
    Sprawdzenie czy macierz należy do SU(n)
    Należy do SU(n), jeśli należy do U(n) i det = 1
    """
    return is_unitary(A) and abs(wyznacznik(A) - 1) < tolerance

def is_symplectic(A):
    """
    Sprawdzenie czy macierz należy do grupy symplektycznej Sp(2n)
    Macierz M jest symplektyczna jeśli jest macierzą niezdeg. antysym. formy dwuliniowej, czyli M^T J M = J gdzie J = [0 I; -I 0]
    """
    n = A.shape[0]
    if n % 2 != 0:
        return False  # Wymiar musi być parzysty
    
    # Tworzymy macierz J
    m = n // 2
    J = np.block([[np.zeros((m, m)), np.eye(m)],
                  [-np.eye(m), np.zeros((m, m))]])
    
    return np.allclose(A.T @ J @ A, J, atol=tolerance)

In [199]:
def check_matrix_groups(A):
    """
    Polecenie zwraca booleanowy słownik, gdzie kluczami są grupy liniowe
    """
    results = {
        'GL': is_GL(A),
        'SL': is_SL(A),
        'O': is_orthogonal(A),
        'SO': is_SO(A),
        'U': is_unitary(A),
        'SU': is_SU(A),
        'Sp': is_symplectic(A)
    }
    return results

### Przykłady

In [1]:
identity = np.eye(2)
rotation = np.array([[0.6, -0.8], [0.8, 0.6]])  # SO(2)
symplectic = np.array([[1, 0, 1, 0], 
                          [0, 1, 0, 1],
                          [0, 0, 1, 0],
                          [0, 0, 0, 1]])  # niesymplekt.
    
print("id:")
print(check_matrix_groups(identity))
    
print("SO:")
print(check_matrix_groups(rotation))
    
print("U:")
print(check_matrix_groups(unitary))
    
print("Sp:")
print(check_matrix_groups(symplectic))

print("A:")
print(check_matrix_groups(A))

<class 'NameError'>: name 'np' is not defined